### ISSUE TITLE
MNP Module + React Native

### ISSUE THREAD

**Issue by kgstefan88** [Lightstreamer/Lightstreamer-example-StockList-client-reactnative#3]
Hi LS team.

Is there a possible way to use lightstreamer mpn module, through react native? We found example only through android native api.

Thanks,
Stefan

**Comment by Bravo27** [comment]
Hi Stefan,

Unfortunately, at this time, you can not interact with the MPN module through the JavaScript client library.

You should use the Android lib just for subscribe to the push notifications you want. 
But I am aware that add a second client lib is something messy and complicated.

Regards,
Giuseppe
